[tools]
bun = "latest"
fnox = "latest"
gh = "latest"
"github:facebook/infer" = "latest"
"github:railwayapp/railpack" = "latest"
go = "latest"
java = "temurin-25"
node = "26"
pnpm = "latest"
python = "3.11"
ruff = "latest"
rust = "latest"
uv = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "pnpm", "yarn"]
trusted_config_paths = [
  "/Users/jonah.snider/conductor/workspaces/",
  "/Users/jonah.snider/programming/sanity",
]
env_file = ".env"
auto_update = true

[settings.github]
credential_command = "gh auth token"

[env]
SANITY_WORKSPACE = "/Users/jonah.snider/programming/sanity"
SANITY_MISE_BOOTSTRAP_VERSION = "4"
